/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_media_format_MPEGParser */

#ifndef _Included_sage_media_format_MPEGParser
#define _Included_sage_media_format_MPEGParser
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_media_format_MPEGParser_REMUX_TS
#define sage_media_format_MPEGParser_REMUX_TS 0L
#undef sage_media_format_MPEGParser_REMUX_PS
#define sage_media_format_MPEGParser_REMUX_PS 1L
/*
 * Class:     sage_media_format_MPEGParser
 * Method:    getMediaAVInf0
 * Signature: (Ljava/lang/String;JZJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sage_media_format_MPEGParser_getMediaAVInf0
  (JNIEnv *, jclass, jstring, jlong, jboolean, jlong);

/*
 * Class:     sage_media_format_MPEGParser
 * Method:    openRemuxer0
 * Signature: (IILjava/io/OutputStream;)J
 */
JNIEXPORT jlong JNICALL Java_sage_media_format_MPEGParser_openRemuxer0
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     sage_media_format_MPEGParser
 * Method:    closeRemuxer0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_media_format_MPEGParser_closeRemuxer0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sage_media_format_MPEGParser
 * Method:    pushRemuxData0
 * Signature: (J[BII)J
 */
JNIEXPORT jlong JNICALL Java_sage_media_format_MPEGParser_pushRemuxData0
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     sage_media_format_MPEGParser
 * Method:    initRemuxDataDone0
 * Signature: (J[BII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sage_media_format_MPEGParser_initRemuxDataDone0
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     sage_media_format_MPEGParser
 * Method:    flushRemuxer0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_media_format_MPEGParser_flushRemuxer0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
