/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_FreetypeFont */

#ifndef _Included_sage_FreetypeFont
#define _Included_sage_FreetypeFont
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_FreetypeFont_PLAIN
#define sage_FreetypeFont_PLAIN 0L
#undef sage_FreetypeFont_BOLD
#define sage_FreetypeFont_BOLD 1L
#undef sage_FreetypeFont_ITALIC
#define sage_FreetypeFont_ITALIC 2L
#undef sage_FreetypeFont_USE_JAVA_FONTS
#define sage_FreetypeFont_USE_JAVA_FONTS 0L
/*
 * Class:     sage_FreetypeFont
 * Method:    loadFreetypeLib0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL _Java_sage_FreetypeFont_loadFreetypeLib0
  (JNIEnv *, jclass);

/*
 * Class:     sage_FreetypeFont
 * Method:    closeFreetypeLib0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL _Java_sage_FreetypeFont_closeFreetypeLib0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sage_FreetypeFont
 * Method:    closeFontFace0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL _Java_sage_FreetypeFont_closeFontFace0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_FreetypeFont
 * Method:    loadFontFace0
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL _Java_sage_FreetypeFont_loadFontFace0
  (JNIEnv *, jobject, jlong, jstring, jint, jint);

/*
 * Class:     sage_FreetypeFont
 * Method:    deriveFontFace0
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL _Java_sage_FreetypeFont_deriveFontFace0
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     sage_FreetypeFont
 * Method:    getGlyphForChar0
 * Signature: (JC)I
 */
JNIEXPORT jint JNICALL _Java_sage_FreetypeFont_getGlyphForChar0
  (JNIEnv *, jobject, jlong, jchar);

/*
 * Class:     sage_FreetypeFont
 * Method:    loadGlyph0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL _Java_sage_FreetypeFont_loadGlyph0
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     sage_FreetypeFont
 * Method:    renderGlyph0
 * Signature: (JLjava/awt/image/BufferedImage;II)I
 */
JNIEXPORT jint JNICALL _Java_sage_FreetypeFont_renderGlyph0
  (JNIEnv *, jobject, jlong, jobject, jint, jint);

/*
 * Class:     sage_FreetypeFont
 * Method:    renderGlyphRaw0
 * Signature: (JLsage/media/image/RawImage;IIII)Lsage/media/image/RawImage;
 */
JNIEXPORT jobject JNICALL _Java_sage_FreetypeFont_renderGlyphRaw0
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jint);

/*
 * Class:     sage_FreetypeFont
 * Method:    getNumGlyphs0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL _Java_sage_FreetypeFont_getNumGlyphs0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_FreetypeFont
 * Method:    getGlyphWidth0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL _Java_sage_FreetypeFont_getGlyphWidth0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_FreetypeFont
 * Method:    getGlyphHeight0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL _Java_sage_FreetypeFont_getGlyphHeight0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_FreetypeFont
 * Method:    getGlyphBearingX0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL _Java_sage_FreetypeFont_getGlyphBearingX0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_FreetypeFont
 * Method:    getGlyphBearingY0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL _Java_sage_FreetypeFont_getGlyphBearingY0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_FreetypeFont
 * Method:    getGlyphAdvance0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL _Java_sage_FreetypeFont_getGlyphAdvance0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_FreetypeFont
 * Method:    getFontHeight0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL _Java_sage_FreetypeFont_getFontHeight0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_FreetypeFont
 * Method:    getFontAscent0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL _Java_sage_FreetypeFont_getFontAscent0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_FreetypeFont
 * Method:    getFontDescent0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL _Java_sage_FreetypeFont_getFontDescent0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
