/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_BasicVideoFrame */

#ifndef _Included_sage_BasicVideoFrame
#define _Included_sage_BasicVideoFrame
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_BasicVideoFrame_FOCUS_TRAVERSABLE_UNKNOWN
#define sage_BasicVideoFrame_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef sage_BasicVideoFrame_FOCUS_TRAVERSABLE_DEFAULT
#define sage_BasicVideoFrame_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef sage_BasicVideoFrame_FOCUS_TRAVERSABLE_SET
#define sage_BasicVideoFrame_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef sage_BasicVideoFrame_TOP_ALIGNMENT
#define sage_BasicVideoFrame_TOP_ALIGNMENT 0.0f
#undef sage_BasicVideoFrame_CENTER_ALIGNMENT
#define sage_BasicVideoFrame_CENTER_ALIGNMENT 0.5f
#undef sage_BasicVideoFrame_BOTTOM_ALIGNMENT
#define sage_BasicVideoFrame_BOTTOM_ALIGNMENT 1.0f
#undef sage_BasicVideoFrame_LEFT_ALIGNMENT
#define sage_BasicVideoFrame_LEFT_ALIGNMENT 0.0f
#undef sage_BasicVideoFrame_RIGHT_ALIGNMENT
#define sage_BasicVideoFrame_RIGHT_ALIGNMENT 1.0f
#undef sage_BasicVideoFrame_serialVersionUID
#define sage_BasicVideoFrame_serialVersionUID -7644114512714619750i64
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef sage_BasicVideoFrame_serialVersionUID
#define sage_BasicVideoFrame_serialVersionUID 4613797578919906343i64
/* Inaccessible static: dbg */
#undef sage_BasicVideoFrame_INCLUDE_SELF
#define sage_BasicVideoFrame_INCLUDE_SELF 1L
#undef sage_BasicVideoFrame_SEARCH_HEAVYWEIGHTS
#define sage_BasicVideoFrame_SEARCH_HEAVYWEIGHTS 1L
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: nameCounter */
#undef sage_BasicVideoFrame_serialVersionUID
#define sage_BasicVideoFrame_serialVersionUID -2728009084054400034i64
#undef sage_BasicVideoFrame_HNAN2MIL
#define sage_BasicVideoFrame_HNAN2MIL 10000i64
#undef sage_BasicVideoFrame_PLAY_SEAM_ADVANCE
#define sage_BasicVideoFrame_PLAY_SEAM_ADVANCE 250i64
#undef sage_BasicVideoFrame_SAGE_DXVA_MPEGA
#define sage_BasicVideoFrame_SAGE_DXVA_MPEGA 1L
#undef sage_BasicVideoFrame_SAGE_DXVA_MPEGB
#define sage_BasicVideoFrame_SAGE_DXVA_MPEGB 2L
#undef sage_BasicVideoFrame_SAGE_DXVA_MPEGC
#define sage_BasicVideoFrame_SAGE_DXVA_MPEGC 3L
#undef sage_BasicVideoFrame_SAGE_DXVA_MPEGD
#define sage_BasicVideoFrame_SAGE_DXVA_MPEGD 4L
/* Inaccessible static: DXVA_MPEG_MODE_NAMES */
#undef sage_BasicVideoFrame_DSCALER_MODE_WEAVE
#define sage_BasicVideoFrame_DSCALER_MODE_WEAVE 1020L
#undef sage_BasicVideoFrame_DSCALER_MODE_TWO_FRAME
#define sage_BasicVideoFrame_DSCALER_MODE_TWO_FRAME 1022L
#undef sage_BasicVideoFrame_DSCALER_MODE_FIELD_BOB
#define sage_BasicVideoFrame_DSCALER_MODE_FIELD_BOB 1024L
#undef sage_BasicVideoFrame_DSCALER_MODE_BOB
#define sage_BasicVideoFrame_DSCALER_MODE_BOB 1021L
#undef sage_BasicVideoFrame_DSCALER_MODE_BLENDED_CLIPPING
#define sage_BasicVideoFrame_DSCALER_MODE_BLENDED_CLIPPING 1023L
#undef sage_BasicVideoFrame_DSCALER_MODE_PLUGIN
#define sage_BasicVideoFrame_DSCALER_MODE_PLUGIN 1025L
/* Inaccessible static: DSCALER_MODE_NAMES */
#undef sage_BasicVideoFrame_SAGE_DEINTERLACE_BOB
#define sage_BasicVideoFrame_SAGE_DEINTERLACE_BOB 1L
#undef sage_BasicVideoFrame_SAGE_DEINTERLACE_WEAVE
#define sage_BasicVideoFrame_SAGE_DEINTERLACE_WEAVE 2L
#undef sage_BasicVideoFrame_SAGE_DEINTERLACE_BOBWEAVE
#define sage_BasicVideoFrame_SAGE_DEINTERLACE_BOBWEAVE 3L
/* Inaccessible static: DEINTERLACE_NAMES */
#undef sage_BasicVideoFrame_ASPECT_FILL
#define sage_BasicVideoFrame_ASPECT_FILL 0L
#undef sage_BasicVideoFrame_ASPECT_SOURCE
#define sage_BasicVideoFrame_ASPECT_SOURCE 1L
#undef sage_BasicVideoFrame_ASPECT_4X3
#define sage_BasicVideoFrame_ASPECT_4X3 2L
#undef sage_BasicVideoFrame_ASPECT_16X9
#define sage_BasicVideoFrame_ASPECT_16X9 3L
/* Inaccessible static: ASPECT_RATIO_NAMES */
#undef sage_BasicVideoFrame_OSD_BUF
#define sage_BasicVideoFrame_OSD_BUF 25L
#undef sage_BasicVideoFrame_TS_DELAY
#define sage_BasicVideoFrame_TS_DELAY 1500i64
#undef sage_BasicVideoFrame_VOL_MAX
#define sage_BasicVideoFrame_VOL_MAX 65535.0f
/* Inaccessible static: chosenOne */
/* Inaccessible static: filterNameCompare */
/* Inaccessible static: class_00024sage_00024BasicVideoFrame */
/*
 * Class:     sage_BasicVideoFrame
 * Method:    inactiveFile0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_inactiveFile0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    initializeMediaFile0
 * Signature: (ILjava/lang/String;IZLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_BasicVideoFrame_initializeMediaFile0
  (JNIEnv *, jobject, jint, jstring, jint, jboolean, jstring);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    getHWND
 * Signature: (Ljava/awt/Canvas;)I
 */
JNIEXPORT jint JNICALL Java_sage_BasicVideoFrame_getHWND
  (JNIEnv *, jclass, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    switchMediaFile0
 * Signature: (Ljava/lang/String;ZILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_BasicVideoFrame_switchMediaFile0
  (JNIEnv *, jobject, jstring, jboolean, jint, jstring);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    timeSelected0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_BasicVideoFrame_timeSelected0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    getMediaTimeHundNano0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sage_BasicVideoFrame_getMediaTimeHundNano0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    getDurationHundNano0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sage_BasicVideoFrame_getDurationHundNano0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    closeMediaFile0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_closeMediaFile0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    getAudioInputPaths0
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_sage_BasicVideoFrame_getAudioInputPaths0
  (JNIEnv *, jclass);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    play0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_play0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    stop0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_stop0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    pause0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_pause0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    frameStep0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_frameStep0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    setAudioDelay0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_setAudioDelay0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    setRate0
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_setRate0
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    getRate0
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_sage_BasicVideoFrame_getRate0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    resizeVideo0
 * Signature: (Ljava/awt/Rectangle;Ljava/awt/Rectangle;Z)V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_resizeVideo0
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    setMute0
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_setMute0
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    getVolume0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sage_BasicVideoFrame_getVolume0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    setVolume0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_setVolume0
  (JNIEnv *, jobject, jint);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    volumeAdjust0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sage_BasicVideoFrame_volumeAdjust0
  (JNIEnv *, jobject, jint);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    setLiveMute0
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_setLiveMute0
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    getLiveMute0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sage_BasicVideoFrame_getLiveMute0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    open350OSD0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sage_BasicVideoFrame_open350OSD0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    close350OSD0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_close350OSD0
  (JNIEnv *, jobject);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    setAlwaysOnTop
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_setAlwaysOnTop
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    playbackControlMessage0
 * Signature: (IJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_BasicVideoFrame_playbackControlMessage0
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    renderVisualization
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_BasicVideoFrame_renderVisualization
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_BasicVideoFrame
 * Method:    renderVideoBitmap0
 * Signature: (I[IIILjava/awt/Rectangle;Ljava/awt/Rectangle;)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_BasicVideoFrame_renderVideoBitmap0
  (JNIEnv *, jobject, jint, jintArray, jint, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
