/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_VideoFrame */

#ifndef _Included_sage_VideoFrame
#define _Included_sage_VideoFrame
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_VideoFrame_FOCUS_TRAVERSABLE_UNKNOWN
#define sage_VideoFrame_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef sage_VideoFrame_FOCUS_TRAVERSABLE_DEFAULT
#define sage_VideoFrame_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef sage_VideoFrame_FOCUS_TRAVERSABLE_SET
#define sage_VideoFrame_FOCUS_TRAVERSABLE_SET 2L
/* Inaccessible static: focusTraversalKeyPropertyNames */
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef sage_VideoFrame_TOP_ALIGNMENT
#define sage_VideoFrame_TOP_ALIGNMENT 0.0f
#undef sage_VideoFrame_CENTER_ALIGNMENT
#define sage_VideoFrame_CENTER_ALIGNMENT 0.5f
#undef sage_VideoFrame_BOTTOM_ALIGNMENT
#define sage_VideoFrame_BOTTOM_ALIGNMENT 1.0f
#undef sage_VideoFrame_LEFT_ALIGNMENT
#define sage_VideoFrame_LEFT_ALIGNMENT 0.0f
#undef sage_VideoFrame_RIGHT_ALIGNMENT
#define sage_VideoFrame_RIGHT_ALIGNMENT 1.0f
#undef sage_VideoFrame_serialVersionUID
#define sage_VideoFrame_serialVersionUID -7644114512714619750i64
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseWheelListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: class_00024java_00024beans_00024PropertyChangeListener */
#undef sage_VideoFrame_serialVersionUID
#define sage_VideoFrame_serialVersionUID 4613797578919906343i64
/* Inaccessible static: dbg */
#undef sage_VideoFrame_INCLUDE_SELF
#define sage_VideoFrame_INCLUDE_SELF 1L
#undef sage_VideoFrame_SEARCH_HEAVYWEIGHTS
#define sage_VideoFrame_SEARCH_HEAVYWEIGHTS 1L
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: nameCounter */
#undef sage_VideoFrame_serialVersionUID
#define sage_VideoFrame_serialVersionUID -2728009084054400034i64
#undef sage_VideoFrame_HNAN2MIL
#define sage_VideoFrame_HNAN2MIL 10000i64
#undef sage_VideoFrame_PLAY_SEAM_ADVANCE
#define sage_VideoFrame_PLAY_SEAM_ADVANCE 250i64
#undef sage_VideoFrame_SAGE_DXVA_MPEGA
#define sage_VideoFrame_SAGE_DXVA_MPEGA 1L
#undef sage_VideoFrame_SAGE_DXVA_MPEGB
#define sage_VideoFrame_SAGE_DXVA_MPEGB 2L
#undef sage_VideoFrame_SAGE_DXVA_MPEGC
#define sage_VideoFrame_SAGE_DXVA_MPEGC 3L
#undef sage_VideoFrame_SAGE_DXVA_MPEGD
#define sage_VideoFrame_SAGE_DXVA_MPEGD 4L
#undef sage_VideoFrame_DSCALER_MODE_WEAVE
#define sage_VideoFrame_DSCALER_MODE_WEAVE 1020L
#undef sage_VideoFrame_DSCALER_MODE_TWO_FRAME
#define sage_VideoFrame_DSCALER_MODE_TWO_FRAME 1022L
#undef sage_VideoFrame_DSCALER_MODE_FIELD_BOB
#define sage_VideoFrame_DSCALER_MODE_FIELD_BOB 1024L
#undef sage_VideoFrame_DSCALER_MODE_BOB
#define sage_VideoFrame_DSCALER_MODE_BOB 1021L
#undef sage_VideoFrame_DSCALER_MODE_BLENDED_CLIPPING
#define sage_VideoFrame_DSCALER_MODE_BLENDED_CLIPPING 1023L
#undef sage_VideoFrame_DSCALER_MODE_PLUGIN
#define sage_VideoFrame_DSCALER_MODE_PLUGIN 1025L
#undef sage_VideoFrame_SAGE_DEINTERLACE_BOB
#define sage_VideoFrame_SAGE_DEINTERLACE_BOB 1L
#undef sage_VideoFrame_SAGE_DEINTERLACE_WEAVE
#define sage_VideoFrame_SAGE_DEINTERLACE_WEAVE 2L
#undef sage_VideoFrame_SAGE_DEINTERLACE_BOBWEAVE
#define sage_VideoFrame_SAGE_DEINTERLACE_BOBWEAVE 3L
#undef sage_VideoFrame_ASPECT_FILL
#define sage_VideoFrame_ASPECT_FILL 0L
#undef sage_VideoFrame_ASPECT_SOURCE
#define sage_VideoFrame_ASPECT_SOURCE 1L
#undef sage_VideoFrame_ASPECT_4X3
#define sage_VideoFrame_ASPECT_4X3 2L
#undef sage_VideoFrame_ASPECT_16X9
#define sage_VideoFrame_ASPECT_16X9 3L
#undef sage_VideoFrame_OSD_BUF
#define sage_VideoFrame_OSD_BUF 25L
#undef sage_VideoFrame_TS_DELAY
#define sage_VideoFrame_TS_DELAY 1500i64
#undef sage_VideoFrame_VOL_MAX
#define sage_VideoFrame_VOL_MAX 65535.0f
/* Inaccessible static: chosenOne */
/* Inaccessible static: filterNameCompare */
/* Inaccessible static: class_00024sage_00024BasicVideoFrame */
#undef sage_VideoFrame_CUT_JUMP_BACKP
#define sage_VideoFrame_CUT_JUMP_BACKP 2000i64
#undef sage_VideoFrame_LOAD_FILE_WAIT
#define sage_VideoFrame_LOAD_FILE_WAIT 200i64
#undef sage_VideoFrame_NEWFILE_INIT_WAIT
#define sage_VideoFrame_NEWFILE_INIT_WAIT 500i64
#undef sage_VideoFrame_MAX_BITRATE_CHANGE
#define sage_VideoFrame_MAX_BITRATE_CHANGE 0.1f
#undef sage_VideoFrame_WATCH_MF
#define sage_VideoFrame_WATCH_MF 100L
#undef sage_VideoFrame_LOAD_MF
#define sage_VideoFrame_LOAD_MF 101L
#undef sage_VideoFrame_SLEEP
#define sage_VideoFrame_SLEEP 102L
#undef sage_VideoFrame_CLOSE_MF
#define sage_VideoFrame_CLOSE_MF 103L
#undef sage_VideoFrame_STD_COMPLETE
#define sage_VideoFrame_STD_COMPLETE 104L
#undef sage_VideoFrame_SEAM_TO_NEXT
#define sage_VideoFrame_SEAM_TO_NEXT 105L
#undef sage_VideoFrame_PAUSE
#define sage_VideoFrame_PAUSE 106L
#undef sage_VideoFrame_PLAY
#define sage_VideoFrame_PLAY 107L
#undef sage_VideoFrame_TIME_ADJUST
#define sage_VideoFrame_TIME_ADJUST 108L
#undef sage_VideoFrame_TIME_SET
#define sage_VideoFrame_TIME_SET 109L
#undef sage_VideoFrame_RATE_ADJUST
#define sage_VideoFrame_RATE_ADJUST 110L
#undef sage_VideoFrame_RATE_SET
#define sage_VideoFrame_RATE_SET 111L
#undef sage_VideoFrame_SEGMENT_ADJUST
#define sage_VideoFrame_SEGMENT_ADJUST 112L
#undef sage_VideoFrame_INACTIVE_FILE
#define sage_VideoFrame_INACTIVE_FILE 113L
#undef sage_VideoFrame_WATCH_COMPLETE_CHECK
#define sage_VideoFrame_WATCH_COMPLETE_CHECK 114L
#undef sage_VideoFrame_PLAY_PAUSE
#define sage_VideoFrame_PLAY_PAUSE 115L
#undef sage_VideoFrame_DIRECT_CONTROL_MSG
#define sage_VideoFrame_DIRECT_CONTROL_MSG 116L
#undef sage_VideoFrame_DVD_CONTROL_MENU
#define sage_VideoFrame_DVD_CONTROL_MENU 201L
#undef sage_VideoFrame_DVD_CONTROL_TITLE_SET
#define sage_VideoFrame_DVD_CONTROL_TITLE_SET 202L
#undef sage_VideoFrame_DVD_CONTROL_CHAPTER_SET
#define sage_VideoFrame_DVD_CONTROL_CHAPTER_SET 205L
#undef sage_VideoFrame_DVD_CONTROL_CHAPTER_NEXT
#define sage_VideoFrame_DVD_CONTROL_CHAPTER_NEXT 206L
#undef sage_VideoFrame_DVD_CONTROL_CHAPTER_PREV
#define sage_VideoFrame_DVD_CONTROL_CHAPTER_PREV 207L
#undef sage_VideoFrame_DVD_CONTROL_ACTIVATE_CURRENT
#define sage_VideoFrame_DVD_CONTROL_ACTIVATE_CURRENT 208L
#undef sage_VideoFrame_DVD_CONTROL_RETURN
#define sage_VideoFrame_DVD_CONTROL_RETURN 209L
#undef sage_VideoFrame_DVD_CONTROL_BUTTON_NAV
#define sage_VideoFrame_DVD_CONTROL_BUTTON_NAV 210L
#undef sage_VideoFrame_DVD_CONTROL_MOUSE_HOVER
#define sage_VideoFrame_DVD_CONTROL_MOUSE_HOVER 211L
#undef sage_VideoFrame_DVD_CONTROL_MOUSE_CLICK
#define sage_VideoFrame_DVD_CONTROL_MOUSE_CLICK 212L
#undef sage_VideoFrame_DVD_CONTROL_ANGLE_CHANGE
#define sage_VideoFrame_DVD_CONTROL_ANGLE_CHANGE 213L
#undef sage_VideoFrame_DVD_CONTROL_SUBTITLE_CHANGE
#define sage_VideoFrame_DVD_CONTROL_SUBTITLE_CHANGE 214L
#undef sage_VideoFrame_DVD_CONTROL_SUBTITLE_TOGGLE
#define sage_VideoFrame_DVD_CONTROL_SUBTITLE_TOGGLE 215L
#undef sage_VideoFrame_DVD_CONTROL_AUDIO_CHANGE
#define sage_VideoFrame_DVD_CONTROL_AUDIO_CHANGE 216L
/*
 * Class:     sage_VideoFrame
 * Method:    goodbye0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sage_VideoFrame_goodbye0
  (JNIEnv *, jobject);

/*
 * Class:     sage_VideoFrame
 * Method:    getFileDuration0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sage_VideoFrame_getFileDuration0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sage_VideoFrame
 * Method:    setSystemVolume0
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_sage_VideoFrame_setSystemVolume0
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     sage_VideoFrame
 * Method:    getSystemVolume0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_sage_VideoFrame_getSystemVolume0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
