/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_LinuxIVTVCaptureManager */

#ifndef _Included_sage_LinuxIVTVCaptureManager
#define _Included_sage_LinuxIVTVCaptureManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sage_LinuxIVTVCaptureManager
 * Method:    getV4LInputName
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sage_LinuxIVTVCaptureManager_getV4LInputName
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     sage_LinuxIVTVCaptureManager
 * Method:    getV4LCardType
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sage_LinuxIVTVCaptureManager_getV4LCardType
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
