/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_HDHomeRunCaptureManager */

#ifndef _Included_sage_HDHomeRunCaptureManager
#define _Included_sage_HDHomeRunCaptureManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sage_HDHomeRunCaptureManager
 * Method:    getDeviceList0
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_sage_HDHomeRunCaptureManager_getDeviceList0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
