/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_DirecTVSerialControl */

#ifndef _Included_sage_DirecTVSerialControl
#define _Included_sage_DirecTVSerialControl
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: loadedLib */
/*
 * Class:     sage_DirecTVSerialControl
 * Method:    openDTVSerial0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sage_DirecTVSerialControl_openDTVSerial0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sage_DirecTVSerialControl
 * Method:    closeHandle0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_DirecTVSerialControl_closeHandle0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DirecTVSerialControl
 * Method:    dtvSerialChannel0
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirecTVSerialControl_dtvSerialChannel0
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
