/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_TranscodeJob */

#ifndef _Included_sage_TranscodeJob
#define _Included_sage_TranscodeJob
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_TranscodeJob_WAITING
#define sage_TranscodeJob_WAITING 1L
#undef sage_TranscodeJob_TRANSCODING
#define sage_TranscodeJob_TRANSCODING 2L
#undef sage_TranscodeJob_TRANSCODING_SEGMENT_COMPLETE
#define sage_TranscodeJob_TRANSCODING_SEGMENT_COMPLETE 3L
#undef sage_TranscodeJob_LIMBO
#define sage_TranscodeJob_LIMBO 4L
#undef sage_TranscodeJob_COMPLETED
#define sage_TranscodeJob_COMPLETED 5L
#undef sage_TranscodeJob_DESTROYED
#define sage_TranscodeJob_DESTROYED -1L
#undef sage_TranscodeJob_TRANSCODE_FAILED
#define sage_TranscodeJob_TRANSCODE_FAILED -2L
/*
 * Class:     sage_TranscodeJob
 * Method:    createTranscodeEngine0
 * Signature: (BBLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sage_TranscodeJob_createTranscodeEngine0
  (JNIEnv *, jclass, jbyte, jbyte, jstring, jstring);

/*
 * Class:     sage_TranscodeJob
 * Method:    doNativeTranscode0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_TranscodeJob_doNativeTranscode0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sage_TranscodeJob
 * Method:    killNativeTranscode0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_TranscodeJob_killNativeTranscode0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
