/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_WMATagParser */

#ifndef _Included_sage_WMATagParser
#define _Included_sage_WMATagParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sage_WMATagParser
 * Method:    extractProperties0
 * Signature: (Ljava/lang/String;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_sage_WMATagParser_extractProperties0
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
