/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_DShowMusicPlayer */

#ifndef _Included_sage_DShowMusicPlayer
#define _Included_sage_DShowMusicPlayer
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: PREFS_ROOT */
/* Inaccessible static: filterNameCompare */
/* Inaccessible static: videoFilterNames */
/* Inaccessible static: audioFilterNames */
/*
 * Class:     sage_DShowMusicPlayer
 * Method:    addMusicVisualization0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_DShowMusicPlayer_addMusicVisualization0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowMusicPlayer
 * Method:    renderVisualization0
 * Signature: (JLjava/awt/Canvas;J)V
 */
JNIEXPORT void JNICALL Java_sage_DShowMusicPlayer_renderVisualization0
  (JNIEnv *, jobject, jlong, jobject, jlong);

/*
 * Class:     sage_DShowMusicPlayer
 * Method:    createGraph0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sage_DShowMusicPlayer_createGraph0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
