/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_EncodingException */

#ifndef _Included_sage_EncodingException
#define _Included_sage_EncodingException
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_EncodingException_serialVersionUID
#define sage_EncodingException_serialVersionUID -3042686055658047285i64
#undef sage_EncodingException_serialVersionUID
#define sage_EncodingException_serialVersionUID -3387516993124229948i64
/* Inaccessible static: ERR_CODE_REZ_NAMES */
#undef sage_EncodingException_DIRECTX_INSTALL
#define sage_EncodingException_DIRECTX_INSTALL -1L
#undef sage_EncodingException_SAGETV_INSTALL
#define sage_EncodingException_SAGETV_INSTALL -2L
#undef sage_EncodingException_FILESYSTEM
#define sage_EncodingException_FILESYSTEM -3L
#undef sage_EncodingException_CAPTURE_DEVICE_INSTALL
#define sage_EncodingException_CAPTURE_DEVICE_INSTALL -4L
#undef sage_EncodingException_SW_VIDEO_COMPRESSION
#define sage_EncodingException_SW_VIDEO_COMPRESSION -5L
#undef sage_EncodingException_HW_VIDEO_COMPRESSION
#define sage_EncodingException_HW_VIDEO_COMPRESSION -6L
#undef sage_EncodingException_SW_AUDIO_COMPRESSION
#define sage_EncodingException_SW_AUDIO_COMPRESSION -7L
#ifdef __cplusplus
}
#endif
#endif
