/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_RoxioFileExport */

#ifndef _Included_sage_RoxioFileExport
#define _Included_sage_RoxioFileExport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sage_RoxioFileExport
 * Method:    openRoxioPlugin0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sage_RoxioFileExport_openRoxioPlugin0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sage_RoxioFileExport
 * Method:    closeRoxioPlugin0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_RoxioFileExport_closeRoxioPlugin0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_RoxioFileExport
 * Method:    addFilesToLibrary0
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sage_RoxioFileExport_addFilesToLibrary0
  (JNIEnv *, jobject, jlong, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
