/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_UIManager */

#ifndef _Included_sage_UIManager
#define _Included_sage_UIManager
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_UIManager_ENABLE_STUDIO
#define sage_UIManager_ENABLE_STUDIO 1L
#undef sage_UIManager_ANTIALIAS
#define sage_UIManager_ANTIALIAS 1L
#undef sage_UIManager_NO_STARTUP
#define sage_UIManager_NO_STARTUP 0L
#undef sage_UIManager_STARTUP_FS
#define sage_UIManager_STARTUP_FS 1L
#undef sage_UIManager_STARTUP_SLEEP
#define sage_UIManager_STARTUP_SLEEP 2L
/*
 * Class:     sage_UIManager
 * Method:    setCompoundWindowRegion
 * Signature: (J[Ljava/awt/Rectangle;[IZ)V
 */
JNIEXPORT void JNICALL Java_sage_UIManager_setCompoundWindowRegion
  (JNIEnv *, jclass, jlong, jobjectArray, jintArray, jboolean);

/*
 * Class:     sage_UIManager
 * Method:    clearWindowRegion
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_UIManager_clearWindowRegion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sage_UIManager
 * Method:    setCursorClip
 * Signature: (Ljava/awt/Rectangle;)V
 */
JNIEXPORT void JNICALL Java_sage_UIManager_setCursorClip
  (JNIEnv *, jclass, jobject);

/*
 * Class:     sage_UIManager
 * Method:    sendMessage
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_UIManager_sendMessage
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     sage_UIManager
 * Method:    findWindow
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sage_UIManager_findWindow
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     sage_UIManager
 * Method:    setAlwaysOnTop
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_sage_UIManager_setAlwaysOnTop
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     sage_UIManager
 * Method:    setAppTaskbarState0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_sage_UIManager_setAppTaskbarState0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     sage_UIManager
 * Method:    getCursorPosX0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sage_UIManager_getCursorPosX0
  (JNIEnv *, jclass);

/*
 * Class:     sage_UIManager
 * Method:    getCursorPosY0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sage_UIManager_getCursorPosY0
  (JNIEnv *, jclass);

/*
 * Class:     sage_UIManager
 * Method:    setHidden0
 * Signature: (ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_UIManager_setHidden0
  (JNIEnv *, jobject, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
