/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_UIUtils */

#ifndef _Included_sage_UIUtils
#define _Included_sage_UIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sage_UIUtils
 * Method:    getHWND
 * Signature: (Ljava/awt/Canvas;)J
 */
JNIEXPORT jlong JNICALL Java_sage_UIUtils_getHWND
  (JNIEnv *, jclass, jobject);

/*
 * Class:     sage_UIUtils
 * Method:    setFullScreenMode
 * Signature: (Ljava/awt/Canvas;Z)J
 */
JNIEXPORT jlong JNICALL Java_sage_UIUtils_setFullScreenMode
  (JNIEnv *, jclass, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
