/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_DirectX9SageRenderer */

#ifndef _Included_sage_DirectX9SageRenderer
#define _Included_sage_DirectX9SageRenderer
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_DirectX9SageRenderer_FONT_TEXTURE_MAP_SIZE
#define sage_DirectX9SageRenderer_FONT_TEXTURE_MAP_SIZE 128L
#undef sage_DirectX9SageRenderer_ANIM_DEBUG
#define sage_DirectX9SageRenderer_ANIM_DEBUG 0L
#undef sage_DirectX9SageRenderer_EPSILON
#define sage_DirectX9SageRenderer_EPSILON 1.0E-4
#undef sage_DirectX9SageRenderer_ELLIPTICAL_DIVISIONS
#define sage_DirectX9SageRenderer_ELLIPTICAL_DIVISIONS 50L
#undef sage_DirectX9SageRenderer_RECT_CORNER_DIVISIONS
#define sage_DirectX9SageRenderer_RECT_CORNER_DIVISIONS 32L
#undef sage_DirectX9SageRenderer_MIN_DIVISIONS
#define sage_DirectX9SageRenderer_MIN_DIVISIONS 4L
#undef sage_DirectX9SageRenderer_D3D_DEBUG
#define sage_DirectX9SageRenderer_D3D_DEBUG 0L
#undef sage_DirectX9SageRenderer_VERTEX_CACHE_SIZE
#define sage_DirectX9SageRenderer_VERTEX_CACHE_SIZE 8192L
#undef sage_DirectX9SageRenderer_VRAM_USAGE_PERCENT
#define sage_DirectX9SageRenderer_VRAM_USAGE_PERCENT 80L
#undef sage_DirectX9SageRenderer_PREMULTIPLY_ALPHA
#define sage_DirectX9SageRenderer_PREMULTIPLY_ALPHA 1L
/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    initDX9SageRenderer0
 * Signature: (IIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_initDX9SageRenderer0
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    cleanupDX9SageRenderer0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sage_DirectX9SageRenderer_cleanupDX9SageRenderer0
  (JNIEnv *, jobject);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    createD3DTextureFromMemory0
 * Signature: (II[I)J
 */
JNIEXPORT jlong JNICALL Java_sage_DirectX9SageRenderer_createD3DTextureFromMemory0__II_3I
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    createD3DTextureFromMemory0
 * Signature: (II[B)J
 */
JNIEXPORT jlong JNICALL Java_sage_DirectX9SageRenderer_createD3DTextureFromMemory0__II_3B
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    createD3DTextureFromMemory0
 * Signature: (IILjava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_sage_DirectX9SageRenderer_createD3DTextureFromMemory0__IILjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    freeD3DTexturePointer0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_DirectX9SageRenderer_freeD3DTexturePointer0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    present0
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_present0
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    clearScene0
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_sage_DirectX9SageRenderer_clearScene0
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    beginScene0
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_beginScene0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    endScene0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sage_DirectX9SageRenderer_endScene0
  (JNIEnv *, jobject);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    stretchBlt0
 * Signature: (JIIIIJIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_stretchBlt0
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    textureMap0
 * Signature: (JFFFFFFFFIIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_textureMap0
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jboolean);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    textureMultiMap0
 * Signature: (J[F[F[F[F[F[F[F[FII[II)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_textureMultiMap0__J_3F_3F_3F_3F_3F_3F_3F_3FII_3II
  (JNIEnv *, jobject, jlong, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jint, jint, jintArray, jint);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    textureDiffuseMap0
 * Signature: (JJFFFFFFFFFFFFIII[D)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_textureDiffuseMap0
  (JNIEnv *, jobject, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint, jint, jdoubleArray);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    textureMultiMap0
 * Signature: (J[F[F[F[F[F[F[F[FII[II[D)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_textureMultiMap0__J_3F_3F_3F_3F_3F_3F_3F_3FII_3II_3D
  (JNIEnv *, jobject, jlong, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jint, jint, jintArray, jint, jdoubleArray);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    fillShape0
 * Signature: ([F[F[IIILjava/awt/Rectangle;)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_fillShape0___3F_3F_3IIILjava_awt_Rectangle_2
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jintArray, jint, jint, jobject);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    fillShape0
 * Signature: ([F[F[IIILjava/awt/Rectangle;[D)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_fillShape0___3F_3F_3IIILjava_awt_Rectangle_2_3D
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jintArray, jint, jint, jobject, jdoubleArray);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    getVideoSnapshot0
 * Signature: (JII[I)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_getVideoSnapshot0
  (JNIEnv *, jobject, jlong, jint, jint, jintArray);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    create3DFont0
 * Signature: (Ljava/lang/String;IZZ)J
 */
JNIEXPORT jlong JNICALL Java_sage_DirectX9SageRenderer_create3DFont0
  (JNIEnv *, jobject, jstring, jint, jboolean, jboolean);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    free3DFont0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_DirectX9SageRenderer_free3DFont0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    renderText0
 * Signature: (Ljava/lang/String;JFFFFI)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_renderText0
  (JNIEnv *, jobject, jstring, jlong, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    getAvailableVideoMemory0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sage_DirectX9SageRenderer_getAvailableVideoMemory0
  (JNIEnv *, jobject);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    getMaximumTextureDimension0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sage_DirectX9SageRenderer_getMaximumTextureDimension0
  (JNIEnv *, jobject);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    hasDirectX90
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_hasDirectX90
  (JNIEnv *, jclass);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    createD3DRenderTarget0
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_sage_DirectX9SageRenderer_createD3DRenderTarget0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    setRenderTarget0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DirectX9SageRenderer_setRenderTarget0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DirectX9SageRenderer
 * Method:    asyncVideoRender0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sage_DirectX9SageRenderer_asyncVideoRender0
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
