/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_PVR350OSDRenderingPlugin */

#ifndef _Included_sage_PVR350OSDRenderingPlugin
#define _Included_sage_PVR350OSDRenderingPlugin
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: loadedLib */
/*
 * Class:     sage_PVR350OSDRenderingPlugin
 * Method:    openOSD0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sage_PVR350OSDRenderingPlugin_openOSD0
  (JNIEnv *, jobject);


/*
 * Class:     sage_PVR350OSDRenderingPlugin
 * Method:    closeOSD0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_PVR350OSDRenderingPlugin_closeOSD0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_PVR350OSDRenderingPlugin
 * Method:    updateOSD0
 * Signature: (J[IIILjava/awt/Rectangle;Ljava/awt/Rectangle;)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_PVR350OSDRenderingPlugin_updateOSD0
  (JNIEnv *, jobject, jlong, jintArray, jint, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
