/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_WindowsServiceControl */

#ifndef _Included_sage_WindowsServiceControl
#define _Included_sage_WindowsServiceControl
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: userLocale */
/* Inaccessible static: coreRez */
/* Inaccessible static: msgFormatRezMap */
/*
 * Class:     sage_WindowsServiceControl
 * Method:    openServiceHandle0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sage_WindowsServiceControl_openServiceHandle0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    closeServiceHandle0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_WindowsServiceControl_closeServiceHandle0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    isServiceAutostart0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_WindowsServiceControl_isServiceAutostart0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    installService0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sage_WindowsServiceControl_installService0
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    setServiceAutostart0
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_WindowsServiceControl_setServiceAutostart0
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    startService0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_WindowsServiceControl_startService0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    stopService0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_WindowsServiceControl_stopService0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    isServiceRunning0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_WindowsServiceControl_isServiceRunning0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    isServiceLoading0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_WindowsServiceControl_isServiceLoading0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    isServiceStopping0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_WindowsServiceControl_isServiceStopping0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    getServiceUser0
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sage_WindowsServiceControl_getServiceUser0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    setServiceUser0
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_WindowsServiceControl_setServiceUser0
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    isServiceRecovery0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_WindowsServiceControl_isServiceRecovery0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_WindowsServiceControl
 * Method:    setServiceRecovery0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_sage_WindowsServiceControl_setServiceRecovery0
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
