/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_DShowTVPlayer */

#ifndef _Included_sage_DShowTVPlayer
#define _Included_sage_DShowTVPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_DShowTVPlayer_OVERLAY_IS_DEFAULT
#define sage_DShowTVPlayer_OVERLAY_IS_DEFAULT 1L
#undef sage_DShowTVPlayer_SAGE_DXVA_MPEGA
#define sage_DShowTVPlayer_SAGE_DXVA_MPEGA 1L
#undef sage_DShowTVPlayer_SAGE_DXVA_MPEGB
#define sage_DShowTVPlayer_SAGE_DXVA_MPEGB 2L
#undef sage_DShowTVPlayer_SAGE_DXVA_MPEGC
#define sage_DShowTVPlayer_SAGE_DXVA_MPEGC 3L
#undef sage_DShowTVPlayer_SAGE_DXVA_MPEGD
#define sage_DShowTVPlayer_SAGE_DXVA_MPEGD 4L
#undef sage_DShowTVPlayer_DSCALER_MODE_WEAVE
#define sage_DShowTVPlayer_DSCALER_MODE_WEAVE 1020L
#undef sage_DShowTVPlayer_DSCALER_MODE_TWO_FRAME
#define sage_DShowTVPlayer_DSCALER_MODE_TWO_FRAME 1022L
#undef sage_DShowTVPlayer_DSCALER_MODE_FIELD_BOB
#define sage_DShowTVPlayer_DSCALER_MODE_FIELD_BOB 1024L
#undef sage_DShowTVPlayer_DSCALER_MODE_BOB
#define sage_DShowTVPlayer_DSCALER_MODE_BOB 1021L
#undef sage_DShowTVPlayer_DSCALER_MODE_BLENDED_CLIPPING
#define sage_DShowTVPlayer_DSCALER_MODE_BLENDED_CLIPPING 1023L
#undef sage_DShowTVPlayer_DSCALER_MODE_PLUGIN
#define sage_DShowTVPlayer_DSCALER_MODE_PLUGIN 1025L
#undef sage_DShowTVPlayer_SAGE_DEINTERLACE_BOB
#define sage_DShowTVPlayer_SAGE_DEINTERLACE_BOB 1L
#undef sage_DShowTVPlayer_SAGE_DEINTERLACE_WEAVE
#define sage_DShowTVPlayer_SAGE_DEINTERLACE_WEAVE 2L
#undef sage_DShowTVPlayer_SAGE_DEINTERLACE_BOBWEAVE
#define sage_DShowTVPlayer_SAGE_DEINTERLACE_BOBWEAVE 3L
/*
 * Class:     sage_DShowTVPlayer
 * Method:    switchLoadTVFile0
 * Signature: (JLjava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_sage_DShowTVPlayer_switchLoadTVFile0
  (JNIEnv *, jobject, jlong, jstring, jstring, jboolean);

/*
 * Class:     sage_DShowTVPlayer
 * Method:    frameStep0
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DShowTVPlayer_frameStep0
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     sage_DShowTVPlayer
 * Method:    addHWDecoderFilter0
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_sage_DShowTVPlayer_addHWDecoderFilter0
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     sage_DShowTVPlayer
 * Method:    createGraph0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sage_DShowTVPlayer_createGraph0
  (JNIEnv *, jobject);

/*
 * Class:     sage_DShowTVPlayer
 * Method:    setupGraphMultifile0
 * Signature: (J[Ljava/lang/String;Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_sage_DShowTVPlayer_setupGraphMultifile0
  (JNIEnv *, jobject, jlong, jobjectArray, jstring, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
