/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_DShowSharedLiveMediaPlayer */

#ifndef _Included_sage_DShowSharedLiveMediaPlayer
#define _Included_sage_DShowSharedLiveMediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sage_DShowSharedLiveMediaPlayer
 * Method:    setVideoHWND0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_sage_DShowSharedLiveMediaPlayer_setVideoHWND0
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     sage_DShowSharedLiveMediaPlayer
 * Method:    getVideoDimensions0
 * Signature: (J)Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_sage_DShowSharedLiveMediaPlayer_getVideoDimensions0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowSharedLiveMediaPlayer
 * Method:    resizeVideo0
 * Signature: (JLjava/awt/Rectangle;Ljava/awt/Rectangle;Z)V
 */
JNIEXPORT void JNICALL Java_sage_DShowSharedLiveMediaPlayer_resizeVideo0
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean);

/*
 * Class:     sage_DShowSharedLiveMediaPlayer
 * Method:    openAudioPreview0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sage_DShowSharedLiveMediaPlayer_openAudioPreview0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     sage_DShowSharedLiveMediaPlayer
 * Method:    setAudioPreview0
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_sage_DShowSharedLiveMediaPlayer_setAudioPreview0
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     sage_DShowSharedLiveMediaPlayer
 * Method:    closeAudioPreview0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_DShowSharedLiveMediaPlayer_closeAudioPreview0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
