/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_VFDInputPlugin */

#ifndef _Included_sage_VFDInputPlugin
#define _Included_sage_VFDInputPlugin
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_VFDInputPlugin_CONTROL_ICON1
#define sage_VFDInputPlugin_CONTROL_ICON1 33L
#undef sage_VFDInputPlugin_CONTROL_ICON2
#define sage_VFDInputPlugin_CONTROL_ICON2 34L
#undef sage_VFDInputPlugin_CONTROL_ICON3
#define sage_VFDInputPlugin_CONTROL_ICON3 35L
#undef sage_VFDInputPlugin_CONTROL_SLEEP
#define sage_VFDInputPlugin_CONTROL_SLEEP 36L
#undef sage_VFDInputPlugin_CONTROL_NORMAL
#define sage_VFDInputPlugin_CONTROL_NORMAL 37L
#undef sage_VFDInputPlugin_CONTROL_FULL_ON
#define sage_VFDInputPlugin_CONTROL_FULL_ON 38L
#undef sage_VFDInputPlugin_CONTROL_BLACK
#define sage_VFDInputPlugin_CONTROL_BLACK 39L
#undef sage_VFDInputPlugin_CONTROL_ICON4
#define sage_VFDInputPlugin_CONTROL_ICON4 40L
#undef sage_VFDInputPlugin_CONTROL_ICON5
#define sage_VFDInputPlugin_CONTROL_ICON5 41L
#undef sage_VFDInputPlugin_ICON1_LOOP
#define sage_VFDInputPlugin_ICON1_LOOP 128L
#undef sage_VFDInputPlugin_ICON1_ALL
#define sage_VFDInputPlugin_ICON1_ALL 64L
#undef sage_VFDInputPlugin_ICON1_PAUSE
#define sage_VFDInputPlugin_ICON1_PAUSE 32L
#undef sage_VFDInputPlugin_ICON1_PLAY
#define sage_VFDInputPlugin_ICON1_PLAY 16L
#undef sage_VFDInputPlugin_ICON1_CD
#define sage_VFDInputPlugin_ICON1_CD 8L
#undef sage_VFDInputPlugin_ICON1_VCD
#define sage_VFDInputPlugin_ICON1_VCD 12L
#undef sage_VFDInputPlugin_ICON1_SVCD
#define sage_VFDInputPlugin_ICON1_SVCD 14L
#undef sage_VFDInputPlugin_ICON1_DTS
#define sage_VFDInputPlugin_ICON1_DTS 1L
#undef sage_VFDInputPlugin_ICON2_DVD
#define sage_VFDInputPlugin_ICON2_DVD 128L
#undef sage_VFDInputPlugin_ICON2_DOLBY
#define sage_VFDInputPlugin_ICON2_DOLBY 64L
#undef sage_VFDInputPlugin_ICON2_PVR
#define sage_VFDInputPlugin_ICON2_PVR 32L
#undef sage_VFDInputPlugin_ICON2_PBC
#define sage_VFDInputPlugin_ICON2_PBC 16L
#undef sage_VFDInputPlugin_ICON2_MP3
#define sage_VFDInputPlugin_ICON2_MP3 8L
#undef sage_VFDInputPlugin_ICON2_COLON1
#define sage_VFDInputPlugin_ICON2_COLON1 4L
#undef sage_VFDInputPlugin_ICON2_COLON2
#define sage_VFDInputPlugin_ICON2_COLON2 2L
#undef sage_VFDInputPlugin_ICON3_PWR
#define sage_VFDInputPlugin_ICON3_PWR 128L
#undef sage_VFDInputPlugin_ICON3_PAUSE
#define sage_VFDInputPlugin_ICON3_PAUSE 32L
#undef sage_VFDInputPlugin_ICON3_HELLO
#define sage_VFDInputPlugin_ICON3_HELLO 16L
#undef sage_VFDInputPlugin_ICON3_ERROR
#define sage_VFDInputPlugin_ICON3_ERROR 8L
#undef sage_VFDInputPlugin_ICON3_EJECT
#define sage_VFDInputPlugin_ICON3_EJECT 4L
#undef sage_VFDInputPlugin_ICON3_LOAD
#define sage_VFDInputPlugin_ICON3_LOAD 2L
#undef sage_VFDInputPlugin_ICON3_NO_DISK
#define sage_VFDInputPlugin_ICON3_NO_DISK 1L
#undef sage_VFDInputPlugin_ICON4_USB
#define sage_VFDInputPlugin_ICON4_USB 128L
#undef sage_VFDInputPlugin_ICON4_1394
#define sage_VFDInputPlugin_ICON4_1394 64L
#undef sage_VFDInputPlugin_ICON4_REAR
#define sage_VFDInputPlugin_ICON4_REAR 32L
#undef sage_VFDInputPlugin_ICON4_FRONT
#define sage_VFDInputPlugin_ICON4_FRONT 16L
#undef sage_VFDInputPlugin_ICON4_REVERSE
#define sage_VFDInputPlugin_ICON4_REVERSE 8L
#undef sage_VFDInputPlugin_ICON4_FORWARD
#define sage_VFDInputPlugin_ICON4_FORWARD 4L
#undef sage_VFDInputPlugin_ICON4_PLAY
#define sage_VFDInputPlugin_ICON4_PLAY 2L
#undef sage_VFDInputPlugin_ICON4_STOP
#define sage_VFDInputPlugin_ICON4_STOP 1L
#undef sage_VFDInputPlugin_ICON5_PRESET
#define sage_VFDInputPlugin_ICON5_PRESET 4L
#undef sage_VFDInputPlugin_ICON5_REC
#define sage_VFDInputPlugin_ICON5_REC 2L
#undef sage_VFDInputPlugin_ICON5_PVR
#define sage_VFDInputPlugin_ICON5_PVR 1L
#undef sage_VFDInputPlugin_VFD_TEXT_DURATION
#define sage_VFDInputPlugin_VFD_TEXT_DURATION 3500L
/*
 * Class:     sage_VFDInputPlugin
 * Method:    sendVFDUpdate0
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_sage_VFDInputPlugin_sendVFDUpdate0
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     sage_VFDInputPlugin
 * Method:    setMediaTime0
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_sage_VFDInputPlugin_setMediaTime0
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     sage_VFDInputPlugin
 * Method:    openPort0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sage_VFDInputPlugin_openPort0
  (JNIEnv *, jobject);

/*
 * Class:     sage_VFDInputPlugin
 * Method:    closePort0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_VFDInputPlugin_closePort0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_VFDInputPlugin
 * Method:    inputThread0
 * Signature: (JLsage/SageTVInputCallback;)V
 */
JNIEXPORT void JNICALL Java_sage_VFDInputPlugin_inputThread0
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
