/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_Ministry */

#ifndef _Included_sage_Ministry
#define _Included_sage_Ministry
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: chosenOne */
#ifdef __cplusplus
}
#endif
#endif
