/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_UserEvent */

#ifndef _Included_sage_UserEvent
#define _Included_sage_UserEvent
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_UserEvent_LEFT
#define sage_UserEvent_LEFT 2L
#undef sage_UserEvent_RIGHT
#define sage_UserEvent_RIGHT 3L
#undef sage_UserEvent_UP
#define sage_UserEvent_UP 4L
#undef sage_UserEvent_DOWN
#define sage_UserEvent_DOWN 5L
#undef sage_UserEvent_PAUSE
#define sage_UserEvent_PAUSE 6L
#undef sage_UserEvent_PLAY
#define sage_UserEvent_PLAY 7L
#undef sage_UserEvent_FF
#define sage_UserEvent_FF 8L
#undef sage_UserEvent_REW
#define sage_UserEvent_REW 9L
#undef sage_UserEvent_TIME_SCROLL
#define sage_UserEvent_TIME_SCROLL 10L
#undef sage_UserEvent_CHANNEL_UP
#define sage_UserEvent_CHANNEL_UP 11L
#undef sage_UserEvent_CHANNEL_DOWN
#define sage_UserEvent_CHANNEL_DOWN 12L
#undef sage_UserEvent_VOLUME_UP
#define sage_UserEvent_VOLUME_UP 13L
#undef sage_UserEvent_VOLUME_DOWN
#define sage_UserEvent_VOLUME_DOWN 14L
#undef sage_UserEvent_TV
#define sage_UserEvent_TV 15L
#undef sage_UserEvent_FASTER
#define sage_UserEvent_FASTER 16L
#undef sage_UserEvent_SLOWER
#define sage_UserEvent_SLOWER 17L
#undef sage_UserEvent_GUIDE
#define sage_UserEvent_GUIDE 18L
#undef sage_UserEvent_POWER
#define sage_UserEvent_POWER 19L
#undef sage_UserEvent_SELECT
#define sage_UserEvent_SELECT 20L
#undef sage_UserEvent_WATCHED
#define sage_UserEvent_WATCHED 21L
#undef sage_UserEvent_RATE_UP
#define sage_UserEvent_RATE_UP 22L
#undef sage_UserEvent_RATE_DOWN
#define sage_UserEvent_RATE_DOWN 23L
#undef sage_UserEvent_INFO
#define sage_UserEvent_INFO 24L
#undef sage_UserEvent_RECORD
#define sage_UserEvent_RECORD 25L
#undef sage_UserEvent_MUTE
#define sage_UserEvent_MUTE 26L
#undef sage_UserEvent_FULL_SCREEN
#define sage_UserEvent_FULL_SCREEN 27L
#undef sage_UserEvent_HOME
#define sage_UserEvent_HOME 28L
#undef sage_UserEvent_OPTIONS
#define sage_UserEvent_OPTIONS 29L
#undef sage_UserEvent_NUM0
#define sage_UserEvent_NUM0 30L
#undef sage_UserEvent_NUM1
#define sage_UserEvent_NUM1 31L
#undef sage_UserEvent_NUM2
#define sage_UserEvent_NUM2 32L
#undef sage_UserEvent_NUM3
#define sage_UserEvent_NUM3 33L
#undef sage_UserEvent_NUM4
#define sage_UserEvent_NUM4 34L
#undef sage_UserEvent_NUM5
#define sage_UserEvent_NUM5 35L
#undef sage_UserEvent_NUM6
#define sage_UserEvent_NUM6 36L
#undef sage_UserEvent_NUM7
#define sage_UserEvent_NUM7 37L
#undef sage_UserEvent_NUM8
#define sage_UserEvent_NUM8 38L
#undef sage_UserEvent_NUM9
#define sage_UserEvent_NUM9 39L
#undef sage_UserEvent_SEARCH
#define sage_UserEvent_SEARCH 40L
#undef sage_UserEvent_SETUP
#define sage_UserEvent_SETUP 41L
#undef sage_UserEvent_LIBRARY
#define sage_UserEvent_LIBRARY 42L
#undef sage_UserEvent_POWER_ON
#define sage_UserEvent_POWER_ON 43L
#undef sage_UserEvent_POWER_OFF
#define sage_UserEvent_POWER_OFF 44L
#undef sage_UserEvent_MUTE_ON
#define sage_UserEvent_MUTE_ON 45L
#undef sage_UserEvent_MUTE_OFF
#define sage_UserEvent_MUTE_OFF 46L
#undef sage_UserEvent_AR_FILL
#define sage_UserEvent_AR_FILL 47L
#undef sage_UserEvent_AR_4X3
#define sage_UserEvent_AR_4X3 48L
#undef sage_UserEvent_AR_16X9
#define sage_UserEvent_AR_16X9 49L
#undef sage_UserEvent_AR_SOURCE
#define sage_UserEvent_AR_SOURCE 50L
#undef sage_UserEvent_VOLUME_UP2
#define sage_UserEvent_VOLUME_UP2 51L
#undef sage_UserEvent_VOLUME_DOWN2
#define sage_UserEvent_VOLUME_DOWN2 52L
#undef sage_UserEvent_CHANNEL_UP2
#define sage_UserEvent_CHANNEL_UP2 53L
#undef sage_UserEvent_CHANNEL_DOWN2
#define sage_UserEvent_CHANNEL_DOWN2 54L
#undef sage_UserEvent_PAGE_UP
#define sage_UserEvent_PAGE_UP 55L
#undef sage_UserEvent_PAGE_DOWN
#define sage_UserEvent_PAGE_DOWN 56L
#undef sage_UserEvent_PAGE_RIGHT
#define sage_UserEvent_PAGE_RIGHT 57L
#undef sage_UserEvent_PAGE_LEFT
#define sage_UserEvent_PAGE_LEFT 58L
#undef sage_UserEvent_PLAY_PAUSE
#define sage_UserEvent_PLAY_PAUSE 59L
#undef sage_UserEvent_PREV_CHANNEL
#define sage_UserEvent_PREV_CHANNEL 60L
#undef sage_UserEvent_FF_2
#define sage_UserEvent_FF_2 61L
#undef sage_UserEvent_REW_2
#define sage_UserEvent_REW_2 62L
#undef sage_UserEvent_LIVE_TV
#define sage_UserEvent_LIVE_TV 63L
#undef sage_UserEvent_DVD_REVERSE_PLAY
#define sage_UserEvent_DVD_REVERSE_PLAY 64L
#undef sage_UserEvent_DVD_CHAPTER_NEXT
#define sage_UserEvent_DVD_CHAPTER_NEXT 65L
#undef sage_UserEvent_DVD_CHAPTER_PREV
#define sage_UserEvent_DVD_CHAPTER_PREV 66L
#undef sage_UserEvent_DVD_MENU
#define sage_UserEvent_DVD_MENU 67L
#undef sage_UserEvent_DVD_TITLE_MENU
#define sage_UserEvent_DVD_TITLE_MENU 68L
#undef sage_UserEvent_DVD_RETURN
#define sage_UserEvent_DVD_RETURN 69L
#undef sage_UserEvent_DVD_SUBTITLE_CHANGE
#define sage_UserEvent_DVD_SUBTITLE_CHANGE 70L
#undef sage_UserEvent_DVD_SUBTITLE_TOGGLE
#define sage_UserEvent_DVD_SUBTITLE_TOGGLE 71L
#undef sage_UserEvent_DVD_AUDIO_CHANGE
#define sage_UserEvent_DVD_AUDIO_CHANGE 72L
#undef sage_UserEvent_DVD_ANGLE_CHANGE
#define sage_UserEvent_DVD_ANGLE_CHANGE 73L
#undef sage_UserEvent_DVD
#define sage_UserEvent_DVD 74L
#undef sage_UserEvent_BACK
#define sage_UserEvent_BACK 75L
#undef sage_UserEvent_FORWARD
#define sage_UserEvent_FORWARD 76L
#undef sage_UserEvent_CUSTOMIZE
#define sage_UserEvent_CUSTOMIZE 77L
#undef sage_UserEvent_CUSTOM1
#define sage_UserEvent_CUSTOM1 78L
#undef sage_UserEvent_CUSTOM2
#define sage_UserEvent_CUSTOM2 79L
#undef sage_UserEvent_CUSTOM3
#define sage_UserEvent_CUSTOM3 80L
#undef sage_UserEvent_CUSTOM4
#define sage_UserEvent_CUSTOM4 81L
#undef sage_UserEvent_CUSTOM5
#define sage_UserEvent_CUSTOM5 82L
#undef sage_UserEvent_DELETE
#define sage_UserEvent_DELETE 83L
#undef sage_UserEvent_MUSIC
#define sage_UserEvent_MUSIC 84L
#undef sage_UserEvent_SCHEDULE
#define sage_UserEvent_SCHEDULE 85L
#undef sage_UserEvent_RECORDINGS
#define sage_UserEvent_RECORDINGS 86L
#undef sage_UserEvent_PICTURE_LIBRARY
#define sage_UserEvent_PICTURE_LIBRARY 87L
#undef sage_UserEvent_VIDEO_LIBRARY
#define sage_UserEvent_VIDEO_LIBRARY 88L
#undef sage_UserEvent_STOP
#define sage_UserEvent_STOP 89L
#undef sage_UserEvent_EJECT
#define sage_UserEvent_EJECT 90L
#undef sage_UserEvent_STOP_EJECT
#define sage_UserEvent_STOP_EJECT 91L
#undef sage_UserEvent_INPUT
#define sage_UserEvent_INPUT 92L
#undef sage_UserEvent_SMOOTH_FF
#define sage_UserEvent_SMOOTH_FF 93L
#undef sage_UserEvent_SMOOTH_REW
#define sage_UserEvent_SMOOTH_REW 94L
#undef sage_UserEvent_ANYTHING
#define sage_UserEvent_ANYTHING 95L
#undef sage_UserEvent_MIN_EVT_ID
#define sage_UserEvent_MIN_EVT_ID 2L
#undef sage_UserEvent_MAX_EVT_ID
#define sage_UserEvent_MAX_EVT_ID 94L
/* Inaccessible static: UENAMES */
/* Inaccessible static: PRETTY_UENAMES */
/* Inaccessible static: nameCodeLookup */
#ifdef __cplusplus
}
#endif
#endif
