/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_DShowDVDPlayer */

#ifndef _Included_sage_DShowDVDPlayer
#define _Included_sage_DShowDVDPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_DShowDVDPlayer_OVERLAY_IS_DEFAULT
#define sage_DShowDVDPlayer_OVERLAY_IS_DEFAULT 1L
/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDVDTitle0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sage_DShowDVDPlayer_getDVDTitle0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDVDTotalTitles0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sage_DShowDVDPlayer_getDVDTotalTitles0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDVDChapter0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sage_DShowDVDPlayer_getDVDChapter0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDVDTotalChapters0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sage_DShowDVDPlayer_getDVDTotalChapters0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDVDDomain0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sage_DShowDVDPlayer_getDVDDomain0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    areDVDButtonsVisible0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DShowDVDPlayer_areDVDButtonsVisible0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDVDAngle0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sage_DShowDVDPlayer_getDVDAngle0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDVDTotalAngles0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sage_DShowDVDPlayer_getDVDTotalAngles0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDVDLanguage0
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sage_DShowDVDPlayer_getDVDLanguage0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDVDAvailableLanguages0
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_sage_DShowDVDPlayer_getDVDAvailableLanguages0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDVDSubpicture0
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sage_DShowDVDPlayer_getDVDSubpicture0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDVDAvailableSubpictures0
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_sage_DShowDVDPlayer_getDVDAvailableSubpictures0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    setDVDRate0
 * Signature: (JF)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DShowDVDPlayer_setDVDRate0
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    seekDVD0
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DShowDVDPlayer_seekDVD0
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getMediaTimeMillis0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sage_DShowDVDPlayer_getMediaTimeMillis0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDurationMillis0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sage_DShowDVDPlayer_getDurationMillis0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    playbackControlMessage0
 * Signature: (JIJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DShowDVDPlayer_playbackControlMessage0
  (JNIEnv *, jobject, jlong, jint, jlong, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    processEvents0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sage_DShowDVDPlayer_processEvents0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    createGraph0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_sage_DShowDVDPlayer_createGraph0
  (JNIEnv *, jobject);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    setupGraph0
 * Signature: (JLjava/lang/String;Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_sage_DShowDVDPlayer_setupGraph0
  (JNIEnv *, jobject, jlong, jstring, jstring, jboolean, jboolean);

/*
 * Class:     sage_DShowDVDPlayer
 * Method:    getDVDAspectRatio0
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_sage_DShowDVDPlayer_getDVDAspectRatio0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
