/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_PlaybackException */

#ifndef _Included_sage_PlaybackException
#define _Included_sage_PlaybackException
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_PlaybackException_serialVersionUID
#define sage_PlaybackException_serialVersionUID -3042686055658047285i64
#undef sage_PlaybackException_serialVersionUID
#define sage_PlaybackException_serialVersionUID -3387516993124229948i64
/* Inaccessible static: ERR_CODE_REZ_NAMES */
#undef sage_PlaybackException_DIRECTX_INSTALL
#define sage_PlaybackException_DIRECTX_INSTALL -1L
#undef sage_PlaybackException_SAGETV_INSTALL
#define sage_PlaybackException_SAGETV_INSTALL -2L
#undef sage_PlaybackException_FILESYSTEM
#define sage_PlaybackException_FILESYSTEM -3L
#undef sage_PlaybackException_VIDEO_RENDER
#define sage_PlaybackException_VIDEO_RENDER -4L
#undef sage_PlaybackException_AUDIO_RENDER
#define sage_PlaybackException_AUDIO_RENDER -5L
#undef sage_PlaybackException_DVD_GENERAL
#define sage_PlaybackException_DVD_GENERAL -6L
#undef sage_PlaybackException_DVD_REGION
#define sage_PlaybackException_DVD_REGION -7L
#undef sage_PlaybackException_DVD_COPYPROTECT
#define sage_PlaybackException_DVD_COPYPROTECT -8L
#undef sage_PlaybackException_DVD_INVALIDOP
#define sage_PlaybackException_DVD_INVALIDOP -9L
#undef sage_PlaybackException_SEEK
#define sage_PlaybackException_SEEK -10L
#ifdef __cplusplus
}
#endif
#endif
