/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_media_image_ImageLoader */

#ifndef _Included_sage_media_image_ImageLoader
#define _Included_sage_media_image_ImageLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sage_media_image_ImageLoader
 * Method:    createThumbnail
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_media_image_ImageLoader_createThumbnail
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

/*
 * Class:     sage_media_image_ImageLoader
 * Method:    loadImageDimensionsFromFile
 * Signature: (Ljava/lang/String;)Lsage/media/image/RawImage;
 */
JNIEXPORT jobject JNICALL Java_sage_media_image_ImageLoader_loadImageDimensionsFromFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     sage_media_image_ImageLoader
 * Method:    loadScaledImageFromFile
 * Signature: (Ljava/lang/String;IIII)Lsage/media/image/RawImage;
 */
JNIEXPORT jobject JNICALL Java_sage_media_image_ImageLoader_loadScaledImageFromFile
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint);

/*
 * Class:     sage_media_image_ImageLoader
 * Method:    scaleRawImage
 * Signature: (Lsage/media/image/RawImage;II[I)Lsage/media/image/RawImage;
 */
JNIEXPORT jobject JNICALL Java_sage_media_image_ImageLoader_scaleRawImage
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     sage_media_image_ImageLoader
 * Method:    freeImage0
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_sage_media_image_ImageLoader_freeImage0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     sage_media_image_ImageLoader
 * Method:    compressImageToFile
 * Signature: (Lsage/media/image/RawImage;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_media_image_ImageLoader_compressImageToFile
  (JNIEnv *, jclass, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
