/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_CVMUtils */

#ifndef _Included_sage_CVMUtils
#define _Included_sage_CVMUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sage_CVMUtils
 * Method:    reloadNameserverCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sage_CVMUtils_reloadNameserverCache
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
