COMPILKIND=release
#LINUX_KERNEL=/sage/dlink/uClinux-sigma/uClinux-2.4

#MRUA=/sage/mrua/mrua_SMP8634_2.8.3.0_GCC4_dev.mips_hdmi
#MRUA=/sage/mrua/mrua_SMP8634_2.8.5.0_GCC4_dev.mips
#MRUA=/sage/mrua/mrua_SMP8634_2.8.7.1_GCC4_dev.mips
MRUA=/sage/mrua/mrua_SMP8634_2.8.5.x_SageTV_GCC4_facsprod_dev.mips
CC=mipsel-linux-gcc
STRIP=mipsel-linux-strip
CFLAGS = -msoft-float -D_DEBUG -DEM8634 -DEM86 -DWITH_RMHDMI -Os -c -D_FILE_OFFSET_BITS=64 -I$(MRUA)/MRUA_src/ -DWITH_FACSPROD=1 -DEM86XX_CHIP=EM86XX_CHIPID_TANGO2 -DEM86XX_REVISION=6 -DEM86XX_MODE=EM86XX_MODEID_STANDALONE -DDEMUX_PSF=1 -DWITHOUT_DTS=1 -DWITH_XLOADED_UCODE=1 -Wa,-mips32r2 -Wa,-mfix7000 -I/sage/smp86xx/build_mips/uclibclib/include
BINDIR=/usr/local/bin

OBJFILES=miniclient.o gfxcmd.o  thread_util.o mediacmd.o malloc.o EM86/bdsubdecoder.o EM86/dvbsubdecoder.o EM86/EM86gfx.o EM86/EM86input.o EM86/EM86media.o  EM86/rmmmimplementation.o EM86/dbgimplementation.o EM86/EM86output.o utils/MiniImage.o utils/swscale.o EM86/SD/outports_options.o EM86/EM86audio.o

miniclient: $(OBJFILES)
	$(CC) -o miniclient $(OBJFILES) -msoft-float -LEM86 \
    -L$(MRUA)/lib/ \
    -L/sage/native/so/Pullreader/lib -L/sage/native/so/tsdirect \
    -L/sage/native/so/VisEngine\
    -L/sage/smp86xx/build_mips/uclibclib/lib \
    -lVisEngine \
    -lm -lpthread \
    -ldcc \
    -lrmhdmi -lrmsha1 -lrmi2c -lruahdmi -lrmcec -lruai2c -lrmedid \
    -lrmmonitoring            \
    -lrmcw                    \
    -lrmcore                  \
    -lrua                     \
    -lllad                    \
    -lrmrtk86 \
    -lPullreader \
    -ltsdirect \
    -lpng12 \
    -ltiff \
    -ljpeg \
    -lungif \
    -lcrypto \
    -lrmzlib \
    -lz \
    -lrmwmaprodecoder \
    -lrmwmaprodecodercore \
    -lgbus

	$(STRIP) --strip-unneeded miniclient

malloc.o: malloc.c
	$(CC) -DFOOTER=1 -DHAVE_MMAP=0 -DHAVE_MORECORE=0 -DONLY_MSPACES=1 -c malloc.c

clean:
	rm -f *.o miniclient miniclient.gdb *.c~ *.h~ STB/*.o EM86/*.o utils/*.o EM86/SD/*.o 
