/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_DVBCaptureDevice */

#ifndef _Included_sage_DVBCaptureDevice
#define _Included_sage_DVBCaptureDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_DVBCaptureDevice_SM2210_ENCODER_MASK
#define sage_DVBCaptureDevice_SM2210_ENCODER_MASK 1L
#undef sage_DVBCaptureDevice_PYTHON2_ENCODER_MASK
#define sage_DVBCaptureDevice_PYTHON2_ENCODER_MASK 2L
#undef sage_DVBCaptureDevice_VBDVCR_ENCODER_MASK
#define sage_DVBCaptureDevice_VBDVCR_ENCODER_MASK 4L
#undef sage_DVBCaptureDevice_MICRONAS_AUDIO_MASK
#define sage_DVBCaptureDevice_MICRONAS_AUDIO_MASK 8L
#undef sage_DVBCaptureDevice_HCW_CAPTURE_MASK
#define sage_DVBCaptureDevice_HCW_CAPTURE_MASK 16L
#undef sage_DVBCaptureDevice_BLACKBIRD_CAPTURE_MASK
#define sage_DVBCaptureDevice_BLACKBIRD_CAPTURE_MASK 32L
#undef sage_DVBCaptureDevice_NEC61051_ENCODER_MASK
#define sage_DVBCaptureDevice_NEC61051_ENCODER_MASK 64L
#undef sage_DVBCaptureDevice_WISGO7007_ENCODER_MASK
#define sage_DVBCaptureDevice_WISGO7007_ENCODER_MASK 128L
/*
 * Class:     sage_DVBCaptureDevice
 * Method:    createEncoder0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sage_DVBCaptureDevice_createEncoder0
  (JNIEnv *, jobject, APISTRING);

/*
 * Class:     sage_DVBCaptureDevice
 * Method:    setupEncoding0
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DVBCaptureDevice_setupEncoding0
  (JNIEnv *, jobject, jlong, APISTRING, jlong);

/*
 * Class:     sage_DVBCaptureDevice
 * Method:    switchEncoding0
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DVBCaptureDevice_switchEncoding0
  (JNIEnv *, jobject, jlong, APISTRING);

/*
 * Class:     sage_DVBCaptureDevice
 * Method:    closeEncoding0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DVBCaptureDevice_closeEncoding0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DVBCaptureDevice
 * Method:    destroyEncoder0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_DVBCaptureDevice_destroyEncoder0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DVBCaptureDevice
 * Method:    eatEncoderData0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sage_DVBCaptureDevice_eatEncoderData0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DVBCaptureDevice
 * Method:    getOutputData0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sage_DVBCaptureDevice_getOutputData0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_DVBCaptureDevice
 * Method:    setChannel0
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DVBCaptureDevice_setChannel0
  (JNIEnv *, jobject, jlong, APISTRING);

/*
 * Class:     sage_DVBCaptureDevice
 * Method:    setInput0
 * Signature: (JIILjava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DVBCaptureDevice_setInput0
  (JNIEnv *, jobject, jlong, jint, jint, APISTRING, jint, jint);

/*
 * Class:     sage_DVBCaptureDevice
 * Method:    setEncoding0
 * Signature: (JLjava/lang/String;Ljava/util/Map;)Z
 */
JNIEXPORT jboolean JNICALL Java_sage_DVBCaptureDevice_setEncoding0
  (JNIEnv *, jobject, jlong, APISTRING, jobject);

/*
 * Class:     sage_DVBCaptureDevice
 * Method:    updateColors0
 * Signature: (JIIIII)[I
 */
JNIEXPORT jintArray JNICALL Java_sage_DVBCaptureDevice_updateColors0
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/* Class:     sage_DVBCaptureDevice
 * Method:    scanChannel0
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT APISTRING JNICALL Java_sage_DVBCaptureDevice_scanChannel0
	(JNIEnv *env, jobject jo, jlong capInfo, APISTRING jnum, APISTRING jcountry, jint streamType );

/* Class:     sage_DVBCaptureDevice
 * Method:    getSignalStrength0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_sage_DVBCaptureDevice_getSignalStrength0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
