/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_media_format_MPEGParser2 */

#ifndef _Included_sage_media_format_MPEGParser2
#define _Included_sage_media_format_MPEGParser2
#ifdef __cplusplus
extern "C" {
#endif
#undef sage_media_format_MPEGParser2_REMUX_TS
#define sage_media_format_MPEGParser2_REMUX_TS 1L
#undef sage_media_format_MPEGParser2_REMUX_PS
#define sage_media_format_MPEGParser2_REMUX_PS 16L
/*
 * Class:     sage_media_format_MPEGParser2
 * Method:    openRemuxer0
 * Signature: (IIIIBSSSSSLjava/io/OutputStream;)J
 */
JNIEXPORT jlong JNICALL Java_sage_media_format_MPEGParser2_openRemuxer0
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyte, jshort, jshort, jshort, jshort, jshort, jobject);

/*
 * Class:     sage_media_format_MPEGParser2
 * Method:    closeRemuxer0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_media_format_MPEGParser2_closeRemuxer0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     sage_media_format_MPEGParser2
 * Method:    pushRemuxData0
 * Signature: (J[BII)J
 */
JNIEXPORT jlong JNICALL Java_sage_media_format_MPEGParser2_pushRemuxData0
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     sage_media_format_MPEGParser2
 * Method:    getAvFormat0
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sage_media_format_MPEGParser2_getAvFormat0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
