/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sage_Mpeg2Transcoder */

#ifndef _Included_sage_Mpeg2Transcoder
#define _Included_sage_Mpeg2Transcoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sage_Mpeg2Transcoder
 * Method:    openTranscode0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_sage_Mpeg2Transcoder_openTranscode0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sage_Mpeg2Transcoder
 * Method:    closeTranscode0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_sage_Mpeg2Transcoder_closeTranscode0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_Mpeg2Transcoder
 * Method:    getFirstTime0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sage_Mpeg2Transcoder_getFirstTime0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_Mpeg2Transcoder
 * Method:    getLastParsedTime0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sage_Mpeg2Transcoder_getLastParsedTime0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_Mpeg2Transcoder
 * Method:    getDurationMillis0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sage_Mpeg2Transcoder_getDurationMillis0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_Mpeg2Transcoder
 * Method:    seek0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_sage_Mpeg2Transcoder_seek0
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     sage_Mpeg2Transcoder
 * Method:    availableToRead0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_sage_Mpeg2Transcoder_availableToRead0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     sage_Mpeg2Transcoder
 * Method:    read0
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_sage_Mpeg2Transcoder_read0
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
