CC=gcc
CFLAGS = -O2 -c -fPIC -D_FILE_OFFSET_BITS=64

#JSDK=-I/usr/local/j2sdk/include/ -I/usr/local/j2sdk/include/linux 
JSDK=-I/opt/jdk1.5.0_02/include -I/opt/jdk1.5.0_02/include/linux

BINDIR=/usr/local/bin

all:libTSnative.so

SRC=TSBuilder.c TSParser.c

libDTVFilter.so: $(OBJFILES)
	$(CC) -shared -W1 -o libTSnative.so $(SRC) $(JSDK)

clean:
	rm -f *.o libTSnative.so *.c~ *.h~
 
